name: Build and Release genpattern

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux_x86_64
            runsOn: ubuntu-24.04
            artifact_name: genpattern_linux_x86_64
          - platform: linux_arm64
            runsOn: ubuntu-24.04-arm
            artifact_name: genpattern_linux_arm64
          - platform: windows_x86_64
            runsOn: windows-latest
            artifact_name: genpattern_windows_x86_64
    runs-on: ${{ matrix.runsOn }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and test genpattern on Linux
        if: ${{ startsWith(matrix.platform, 'linux') }}
        uses: ./.github/actions/build-genpattern-linux
        with:
          artifact_name: ${{ matrix.artifact_name }}_${{ github.sha }}

      - name: Build and test genpattern on Windows
        if: ${{ startsWith(matrix.platform, 'windows') }}
        uses: ./.github/actions/build-genpattern-windows
        with:
          artifact_name: ${{ matrix.artifact_name }}_${{ github.sha }}
  
  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_windows_x86_64_${{ github.sha }}

      - name: Create Windows ZIP
        run: zip -j genpattern.windows.x64.zip genpattern.dll && rm genpattern.dll
        shell: bash

      - name: Download Linux x86_64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_linux_x86_64_${{ github.sha }}

      - name: Create Linux x86_64 tar.gz
        run: tar -czvf genpattern.linux.x86_64.tar.gz libgenpattern.so && rm libgenpattern.so
        shell: bash

      - name: Download Linux arm64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_linux_arm64_${{ github.sha }}

      - name: Create Linux arm64 tar.gz
        run: tar -czvf genpattern.linux.arm64.tar.gz libgenpattern.so && rm libgenpattern.so
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body: "Automatically created release for ${{ github.ref_name }}"
          files: |
            genpattern.windows.x64.zip
            genpattern.linux.x86_64.tar.gz
            genpattern.linux.arm64.tar.gz